language: node_js

node_js:
  - "10"
  - "12"

install:
  - npm install

addons:
  sonarcloud:
    organization: "luanp-github"

script:
  - npm test
  - sonar-scanner

after_success:
  - npm run coverage
